In [1]:
import pandas as pd

In [2]:
curr_folder = 'real1'
data_folder = '/Users/ngocanh/Documents/Master/in progress/CS4220'

In [11]:
df1 = pd.read_csv(f'{data_folder}/snv-parse-{curr_folder}_all_features.txt', delimiter='\t')
df_label = pd.read_csv(f'{data_folder}/{curr_folder}/{curr_folder}_truth.bed', delimiter='\t')
df1['Chr'] = df1['Chr'].astype(str)
df_label['Chr'] = df_label['Chr'].astype(str)
df_joined = df1.merge(df_label, on=['Chr', 'START_POS_REF', 'END_POS_REF'], how='outer', indicator=True)
df_joined[df_joined['_merge'] == 'right_only']

/var/folders/_0/ztgrcgnj1bd__vhjt7plwd2w0000gn/T/ipykernel_13152/4102129954.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(f'/Users/ngocanh/Documents/Master/in progress/CS4220/snv-parse-{curr_folder}_all_features.txt', delimiter='\t')

,Chr,START_POS_REF,END_POS_REF,REF,ALT,REF_MFVdVs,ALT_MFVdVs,Sample_Name,FILTER_Mutect2,FILTER_Freebayes,...,vs_SPV,vs_SSC,vd_AF,vd_DP,vd_MSI,vd_SAMPLE,vd_SOR,vd_SSF,vd_VD,_merge
1444,1,105553679,105553679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
3463,1,236070218,236070218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4075,10,27264403,27264403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4094,10,29381097,29381097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
4168,10,37702476,37702476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
5228,10,55821614,55821614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
5399,10,75481547,75481547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
5610,10,100974667,100974667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
6542,11,38267894,38267894,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
7466,11,68115417,68115417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
7716,11,90678328,90678328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
7721,11,91468563,91468563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
9047,12,42665316,42665316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
9436,12,84566996,84566996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
10600,13,73828680,73828680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
10700,13,87705328,87705328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
11450,14,30226911,30226911,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
12220,14,106327637,106327637,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
13697,16,5914105,5914105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
16435,17,37421088,37421088,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
17036,18,4202589,4202589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
17461,18,26188355,26188355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
17629,18,49977665,49977665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
19953,2,51989311,51989311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
21104,2,117632946,117632946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
21655,2,154396626,154396626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
21674,2,157982471,157982471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
22522,20,9735395,9735395,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
26121,3,34190777,34190777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
26374,3,61600000,61600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
26706,3,87527546,87527546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
27094,3,119696016,119696016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
28243,4,20294893,20294893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29284,4,92114472,92114472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
29802,4,157682870,157682870,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31288,5,57625733,57625733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31532,5,88890356,88890356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
31674,5,109437603,109437603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
32760,6,32948607,32948607,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
33273,6,83460027,83460027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
37166,7,146115420,146115420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
37688,8,4065944,4065944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
38822,8,95172500,95172500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
41870,9,106512241,106512241,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only
48063,Y,6407994,6407994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,right_only

In [12]:
m2_cols = [col.split('_')[1] for col in df_joined.columns if col.startswith('m2_')]
f_cols = [col.split('_')[1] for col in df_joined.columns if col.startswith('f_')]
vs_cols = [col.split('_')[1] for col in df_joined.columns if col.startswith('vs_')]
vd_cols = [col.split('_')[1] for col in df_joined.columns if col.startswith('vd_')]
print(f"Mutect2 features: {m2_cols}")
print(f"Freebayes features: {f_cols}")
print(f"Varscan features: {vs_cols}")
print(f"Vardict features: {vd_cols}")

Mutect2 features: ['MQ', 'FS', 'MQ0', 'MQRankSum', 'NLOD', 'PON']
Freebayes features: ['MQMR', 'MQM', 'AB', 'ABP', 'AC', 'AF', 'AN', 'AO', 'GTI', 'LEN', 'MEANALT', 'MIN', 'NS', 'NUMALT', 'ODDS', 'PAIRED', 'PAIREDR', 'PAO', 'PQA', 'PQR', 'PRO', 'QA', 'QR', 'RO', 'RPL', 'RPP']
Varscan features: ['DP', 'GPV', 'SPV', 'SSC']
Vardict features: ['AF', 'DP', 'MSI', 'SAMPLE', 'SOR', 'SSF', 'VD']

In [14]:
df_joined['Missed_pos'] = df_joined['Chr'].astype(str) + '_' + df_joined['START_POS_REF'].astype(str)
missed_pos = df_joined['Missed_pos'].unique()
df_joined.drop(['Missed_pos'], axis=1, inplace=True)
missed_pos

array(['1_13110', '1_15015', '1_16949', ..., 'Y_59030255', 'Y_59031439',
       'Y_59031799'], dtype=object)

In [17]:
df_missed = pd.DataFrame(columns=df_joined.columns)
# df_missed.columns
algo_name_list = ['mutect2', 'varscan', 'vardict', 'freebayes']
sample_name = df_joined['Sample_Name'].unique()[0]
for chr_pos in missed_pos:
    print(f"Processing {chr_pos}")
    chr = chr_pos.split('_')[0]
    pos = chr_pos.split('_')[1]

    curr_row = {}
    curr_row['Chr'] = chr
    curr_row['START_POS_REF'] = pos
    curr_row['END_POS_REF'] = pos
    curr_row['FILTER_Mutect2'] = False
    curr_row['FILTER_Freebayes'] = False
    curr_row['FILTER_Vardict'] = False
    curr_row['FILTER_Varscan'] = False

    curr_row['Sample_Name'] = sample_name
    for algo_name in algo_name_list:
        print(algo_name)
        if algo_name == 'mutect2':
            algo_features = m2_cols
            prefix = 'm2_'
        elif algo_name == 'varscan':
            algo_features = vs_cols
            prefix = 'vs_'
        elif  algo_name == 'vardict':
            algo_features = vd_cols
            prefix = 'vd_'
        elif algo_name == 'freebayes':
            algo_features = f_cols
            prefix = 'f_'
        with open('{}/{}/{}-{}.vcf'.format(data_folder, curr_folder, curr_folder, algo_name), 'r') as f:
            lines = [line.rstrip() for line in f if line.startswith(f'{chr}\t{pos}\t')]
            if len(lines) == 1:

                m2_ref = 'NA'
                m2_alt = 'NA'
                f_ref = 'NA'
                f_alt = 'NA'
                vd_ref = 'NA'
                vd_alt = 'NA'
                vs_ref = 'NA'
                vs_alt = 'NA'

                line = lines[0]
                cols = line.split('\t')
                if algo_name == 'mutect2':
                    m2_ref = cols[3]
                    m2_alt = cols[4]
                elif algo_name == 'varscan':
                    vs_ref = cols[3]
                    vs_alt = cols[4]
                elif  algo_name == 'vardict':
                    vd_ref = cols[3]
                    vd_alt = cols[4]
                elif algo_name == 'freebayes':
                    f_ref = cols[3]
                    f_alt = cols[4]
                
                info = cols[7]
                feature_list = info.split(';')
                for feature in feature_list:

                    if len(feature.split('=')) == 1:
                        feature_name = feature.split('=')[0]
                        feature_val = None
                    else:
                        feature_name = feature.split('=')[0]
                        feature_val = feature.split('=')[1]
                    if feature_name in algo_features:
                        curr_row[prefix + feature_name] = feature_val
            elif len(lines) > 1:
                input("Unexpected: algo contains more than 1 entry for 1 position")
            else:
                for feature_name in algo_features:
                    curr_row[prefix + feature_name] = None
    for i in [m2_ref, f_ref, vd_ref, vs_ref]:
        if i != 'NA':
            curr_row['REF'] = i
            break
    for i in [m2_alt, f_alt, vd_alt, vs_alt]:
        if i != 'NA':
            curr_row['ALT'] = i
            break
    curr_row['REF_MFVdVs'] = f'{m2_ref}/{f_ref}/{vd_ref}/{vs_ref}/'
    curr_row['ALT_MFVdVs'] = f'{m2_alt}/{f_alt}/{vd_alt}/{vs_alt}/'
    curr_row['_merge'] = 'right_only'
    for col in df_missed:
        if col not in curr_row.keys():
            curr_row[col] = None
        
    df_missed = df_missed._append(curr_row, ignore_index = True) 
    print(df_missed)

Processing 1_13110
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None

[1 rows x 57 columns]
Processing 1_15015
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None

[2 rows x 57 columns]
Processing 1_16949
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None

[3 rows x 57 columns]
Processing 1_40552
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None

[4 rows x 57 columns]
Processing 1_46907
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None

[5 rows x 57 columns]
Processing 1_63236
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
5   1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None
5          False            False  ...     13    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None
5        None     None     None  None  right_only  None

[6 rows x 57 columns]
Processing 1_63239
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
5   1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
6   1         63239       63239   C   T  NA/NA/NA/C/  NA/NA/NA/T/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None
5          False            False  ...     13    None  None   None
6          False            False  ...     15    None  None   None

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None
5        None     None     None  None  right_only  None
6        None     None     None  None  right_only  None

[7 rows x 57 columns]
Processing 1_64613
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
5   1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
6   1         63239       63239   C   T  NA/NA/NA/C/  NA/NA/NA/T/  icgc_cll-T
7   1         64613       64613   T   A  NA/NA/T/NA/  NA/NA/A/NA/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None
5          False            False  ...     13    None  None   None
6          False            False  ...     15    None  None   None
7          False            False  ...     15  0.1176    17      2

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None
5        None     None     None  None  right_only  None
6        None     None     None  None  right_only  None
7  icgc_cll-T  3.23828  0.34163     2  right_only  None

[8 rows x 57 columns]
Processing 1_70300
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
5   1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
6   1         63239       63239   C   T  NA/NA/NA/C/  NA/NA/NA/T/  icgc_cll-T
7   1         64613       64613   T   A  NA/NA/T/NA/  NA/NA/A/NA/  icgc_cll-T
8   1         70300       70300   C   T  NA/NA/C/NA/  NA/NA/T/NA/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None
5          False            False  ...     13    None  None   None
6          False            False  ...     15    None  None   None
7          False            False  ...     15  0.1176    17      2
8          False            False  ...      6  0.2857    14      3

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None
5        None     None     None  None  right_only  None
6        None     None     None  None  right_only  None
7  icgc_cll-T  3.23828  0.34163     2  right_only  None
8  icgc_cll-T      inf  0.04889     4  right_only  None

[9 rows x 57 columns]
Processing 1_71992
mutect2
varscan
vardict
freebayes
  Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs Sample_Name  \
0   1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/  icgc_cll-T
1   1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/  icgc_cll-T
2   1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/  icgc_cll-T
3   1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
4   1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
5   1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/  icgc_cll-T
6   1         63239       63239   C   T  NA/NA/NA/C/  NA/NA/NA/T/  icgc_cll-T
7   1         64613       64613   T   A  NA/NA/T/NA/  NA/NA/A/NA/  icgc_cll-T
8   1         70300       70300   C   T  NA/NA/C/NA/  NA/NA/T/NA/  icgc_cll-T
9   1         71992       71992   T   G  NA/T/NA/NA/  NA/G/NA/NA/  icgc_cll-T

  FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP vd_MSI  \
0          False            False  ...      2  0.1127   213      2
1          False            False  ...      5    None  None   None
2          False            False  ...     16    None  None   None
3          False            False  ...     26    None  None   None
4          False            False  ...     17    None  None   None
5          False            False  ...     13    None  None   None
6          False            False  ...     15    None  None   None
7          False            False  ...     15  0.1176    17      2
8          False            False  ...      6  0.2857    14      3
9          False            False  ...   None  0.5455    11      3

    vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0  icgc_cll-T  1.36189  0.23427    24  right_only  None
1        None     None     None  None  right_only  None
2        None     None     None  None  right_only  None
3        None     None     None  None  right_only  None
4        None     None     None  None  right_only  None
5        None     None     None  None  right_only  None
6        None     None     None  None  right_only  None
7  icgc_cll-T  3.23828  0.34163     2  right_only  None
8  icgc_cll-T      inf  0.04889     4  right_only  None
9  icgc_cll-T  10.8627  0.00822     6  right_only  None

[10 rows x 57 columns]
Processing 1_76934
mutect2
varscan
vardict
freebayes
   Chr START_POS_REF END_POS_REF REF ALT   REF_MFVdVs   ALT_MFVdVs  \
0    1         13110       13110   G   A  NA/NA/G/NA/  NA/NA/A/NA/
1    1         15015       15015   G   C  NA/NA/NA/G/  NA/NA/NA/C/
2    1         16949       16949   A   C  NA/NA/NA/A/  NA/NA/NA/C/
3    1         40552       40552   T   C  NA/NA/NA/T/  NA/NA/NA/C/
4    1         46907       46907   T   C  NA/NA/NA/T/  NA/NA/NA/C/
5    1         63236       63236   T   C  NA/NA/NA/T/  NA/NA/NA/C/
6    1         63239       63239   C   T  NA/NA/NA/C/  NA/NA/NA/T/
7    1         64613       64613   T   A  NA/NA/T/NA/  NA/NA/A/NA/
8    1         70300       70300   C   T  NA/NA/C/NA/  NA/NA/T/NA/
9    1         71992       71992   T   G  NA/T/NA/NA/  NA/G/NA/NA/
10   1         76934       76934   G   C  NA/NA/NA/G/  NA/NA/NA/C/

   Sample_Name FILTER_Mutect2 FILTER_Freebayes  ... vs_SSC   vd_AF vd_DP  \
0   icgc_cll-T          False            False  ...      2  0.1127   213
1   icgc_cll-T          False            False  ...      5    None  None
2   icgc_cll-T          False            False  ...     16    None  None
3   icgc_cll-T          False            False  ...     26    None  None
4   icgc_cll-T          False            False  ...     17    None  None
5   icgc_cll-T          False            False  ...     13    None  None
6   icgc_cll-T          False            False  ...     15    None  None
7   icgc_cll-T          False            False  ...     15  0.1176    17
8   icgc_cll-T          False            False  ...      6  0.2857    14
9   icgc_cll-T          False            False  ...   None  0.5455    11
10  icgc_cll-T          False            False  ...     13    None  None

   vd_MSI   vd_SAMPLE   vd_SOR   vd_SSF vd_VD      _merge f_MIN
0       2  icgc_cll-T  1.36189  0.23427    24  right_only  None
1    None        None     None     None  None  right_only  None
2    None        None     None     None  None  right_only  None
3    None        None     None     None  None  right_only  None
4    None        None     None     None  None  right_only  None
5    None        None     None     None  None  right_only  None
6    None        None     None     None  None  right_only  None
7       2  icgc_cll-T  3.23828  0.34163     2  right_only  None
8       3  icgc_cll-T      inf  0.04889     4  right_only  None
9       3  icgc_cll-T  10.8627  0.00822     6  right_only  None
10   None        None     None     None  None  right_only  None

[11 rows x 57 columns]
Processing 1_83057
mutect2
varscan
vardict
freebayes

KeyboardInterrupt:

In [20]:
df_missed

   a    b
0  1  dsf

In [ ]:
df_missed